### ISSUE TITLE
希望支持非 HTTP 标准方法的路由注册。

### ISSUE THREAD

**Issue by xmx** [xgfone/ship#18]
我基于 ship 开发 `WebDAV` 文件共享时，想把 `/dav` `/dav/*` 这个路径作为 `WebDAV` 的文件共享路径，`WebDAV` 是基于 HTTP 的协议，但是在 HTTP 标准的方法中[扩展了一些方法](https://www.rfc-editor.org/rfc/rfc4918#section-9)，如 `MKCOL` `COPY` `LOCK` `UNLOCK` 等方法，但是当前路由只有 `GET` `POST` `PUT` ... 这些标准 HTTP 方法。希望能支持除此之外的其他方法。

代码示例如下：

```go
package main

import (
	"net/http"

	"github.com/xgfone/ship/v5"
	"golang.org/x/net/webdav"
)

func main() {
	h := &webdav.Handler{
		FileSystem: webdav.Dir("/"),
		LockSystem: webdav.NewMemLS(),
	}

	fn := func(c *ship.Context) error {
		req := c.Request()
		path := c.Param("path")
		req.URL.Path = "/" + path
		h.ServeHTTP(c.ResponseWriter(), req)
		return nil
	}

	methods := []string{
		http.MethodOptions, http.MethodGet, http.MethodHead, http.MethodPost, http.MethodDelete,
		http.MethodPut, "MKCOL", "COPY", "MOVE", "LOCK", "UNLOCK", "PROPFIND", "PROPPATCH",
	}
	sh := ship.Default()
	sh.Route("/dav").Method(fn, methods...)
	sh.Route("/dav/*path").Method(fn, methods...)

	_ = http.ListenAndServe(":8080", sh)
}
```

https://github.com/xgfone/ship/blob/405a71df982a3bdd7fd2925b85610949cad78d6c/router/echo/echo.go#L124-L163

**Comment by xmx** [comment]
标准库在校验 HTTP 方法时，也是兼容 `extension-method` 的：
https://github.com/golang/go/blob/8fb9565832e6dbacaaa057ffabc251a9341f8d23/src/net/http/request.go#L821-L836

简单看了下 gin 和 echo 路由注册，也是支持扩展方法的。
https://github.com/gin-gonic/gin/blob/153b229fcc6570bac0674d02ab1a629804f29072/gin.go#L325-L331
https://github.com/labstack/echo/blob/master/router.go#L55

[RFC2616](https://www.rfc-editor.org/rfc/rfc2616#section-5.1.1) 也标明了有 `extension-method`

**Comment by xmx** [comment]
感谢您如此迅速的采纳，今天晚上添加了 GitHub 同名微信，应该是你本人，希望能够学习交流😁。
我刚刚更新并使用出现了个 BUG，应该是哪个地方没初始化好 `others` map，添加其他方法时会 panic，复现代码如下：

```go
package main

import "github.com/xgfone/ship/v5"

func main() {
	handle := ship.OkHandler()
	sh := ship.Default()
	sh.Route("/webdav").Method(handle, "LOCK") // panic
}
```

```text
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/xgfone/ship/v5/router/echo.(*methodHandler).AddHandler(0xc000119a20?, {0x11c6825?, 0x4?}, {0x11b6000, 0xc000068690})
        /Users/user/Documents/Code/Golang/pkg/mod/github.com/xgfone/ship/v5@v5.3.0/router/echo/echo.go:183 +0x46a
github.com/xgfone/ship/v5/router/echo.(*Router).insert(0xc00024b2d0?, {0x0, 0x0}, {0x11c6825, 0x4}, {0x11c74a3, 0x7}, {0x11c74a3?, 0x0?}, 0x0, ...)
        /Users/user/Documents/Code/Golang/pkg/mod/github.com/xgfone/ship/v5@v5.3.0/router/echo/echo.go:627 +0x671
github.com/xgfone/ship/v5/router/echo.(*Router).Add(0xc00013c2a0, {0x0, 0x0}, {0x11c74a3, 0x7}, {0x11c6825?, 0x11b6000?}, {0x11b6000, 0xc000068690})
        /Users/user/Documents/Code/Golang/pkg/mod/github.com/xgfone/ship/v5@v5.3.0/router/echo/echo.go:584 +0x8bc
github.com/xgfone/ship/v5.(*Ship).AddRoute(0xc000002300, {{0x11c74a3, 0x7}, {0x11c6825, 0x4}, {0x0, 0x0}, 0x11f1540, {0x0, 0x0}})
        /Users/user/Documents/Code/Golang/pkg/mod/github.com/xgfone/ship/v5@v5.3.0/ship_route.go:109 +0xea
github.com/xgfone/ship/v5.(*Ship).AddRoutes(...)
        /Users/user/Documents/Code/Golang/pkg/mod/github.com/xgfone/ship/v5@v5.3.0/ship_route.go:83
github.com/xgfone/ship/v5.(*RouteBuilder).Method(0xc0000244e0, 0x0?, {0xc000119f60?, 0xc000002300?, 0x0?})
        /Users/user/Documents/Code/Golang/pkg/mod/github.com/xgfone/ship/v5@v5.3.0/ship_route_builder.go:148 +0x12b
main.main()
        /Users/user/Documents/Code/Golang/src/github.com/xmx/manager/main/main.go:8 +0x9e
```

**Comment by xmx** [comment]
比较奇怪的是：👆上面的代码 panic 发生在 macOS 系统上，同样的复制的代码在 Windows 上正常运行。

**Comment by xgfone** [comment]
有两处 `methodHandler` 被重置了，重置时将 `others` 变成为 `nil` 所致。

已修复，尝试使用 `v5.3.1` 再在 macOS 上试一下？

**Comment by xmx** [comment]
好的，macOS 在家里面，晚上下班后测试反馈

**Comment by xmx** [comment]
自测无 BUG
